image:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent
 
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
#  storageClass: standard
  annotations: {}
 
  

restartPolicy: Never
env:
  name: VCAP_SERVICES
  value: {"postgres":[{"name":"EdgeDatabase","credentials":{"name":"postgres","host":"database-service","port":"5432","username":"postgres","password":"Siemens123"}}]}
